# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detQ_rcpp <- function(M) {
    .Call(`_qspray_detQ_rcpp`, M)
}

qspray_maker <- function(Powers, coeffs) {
    .Call(`_qspray_qspray_maker`, Powers, coeffs)
}

qspray_add <- function(Powers1, coeffs1, Powers2, coeffs2) {
    .Call(`_qspray_qspray_add`, Powers1, coeffs1, Powers2, coeffs2)
}

qspray_subtract <- function(Powers1, coeffs1, Powers2, coeffs2) {
    .Call(`_qspray_qspray_subtract`, Powers1, coeffs1, Powers2, coeffs2)
}

qspray_mult <- function(Powers1, coeffs1, Powers2, coeffs2) {
    .Call(`_qspray_qspray_mult`, Powers1, coeffs1, Powers2, coeffs2)
}

test <- function() {
    invisible(.Call(`_qspray_test`))
}

qspray_equality <- function(Powers1, coeffs1, Powers2, coeffs2) {
    .Call(`_qspray_qspray_equality`, Powers1, coeffs1, Powers2, coeffs2)
}

qspray_power <- function(Powers, coeffs, n) {
    .Call(`_qspray_qspray_power`, Powers, coeffs, n)
}

